title: rajavardhan reddy
#logo: /assets/headshot_circle.png
description: Thanks for stopping by my portfolio. Grab a coffee and please browse around the projects that are of your interest!  <br /> <br /> Feel free to contact me via my email! <br /> rajareddy4534@gmail.com
show_downloads: false
google_analytics: true
theme: jekyll-theme-slate
